### ISSUE TITLE
Fix for navigating between education & internship

### ISSUE THREAD

**Issue by Andy0926** [poojagarva28/myportfolio#1]
# Users are unable to view education tab after clicking on the internship

The source of issue is because use of same id
Quick fix is to modify 2 & 3 to **educations** instead of education :)

![image](https://user-images.githubusercontent.com/18086860/184411722-bc70d600-50d0-48a9-8563-a3b037cd0987.png)

**Comment by poojagarva28** [comment]
Thanks, Its solved.
